// PROJECT 2/itday-qwik/src/components/header/Navigation/Navigation.tsx
import { component$, useStore } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import { TurnDownArrowRightLight } from "~/packages/utils/icons";

const Navigation = component$(() => {
  const store = useStore({
    bars: false,
  });

  return (
    <>
      <div
        className="py-4 border-t-[1.5px] border-black w-full row-span-full space-y-4"
        style="opacity: 1; transform: translateY(0%) translateZ(0px);"
      >
        <h3 className="text-textGrey text-xs capitalize">Navigation</h3>
        <nav className="flex flex-col space-y-3">
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            Generate Alpha
          </a>
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            Our Platforms
          </a>
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            <TurnDownArrowRightLight />
            <span>Fountry</span>
          </a>
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            <TurnDownArrowRightLight />
            <span>gotham</span>
          </a>
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            <TurnDownArrowRightLight />
            <span>apollo</span>
          </a>
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            Offerings
          </a>
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            Impact Studies
          </a>
          <a
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/"
          >
            Careers
          </a>

          <Link
            className="text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide undefined"
            href="/about"
            onClick$={() => {
                store.bars = true;
              }}          >
            About iTDAY
          </Link>
        </nav>
      </div>
    </>
  );
});

export default Navigation;

// PROJECT 1/itday-v2.0.0/modules/navigation/Navigation/navigation.tsx
import Link from "next/link";
import { routes } from "../../../packages/constants/routes";
import { TurnDownArrowRight } from "../../../packages/utils/icons";

const Navigation = () => {
  return (
    <nav className="flex flex-col space-y-3">
      <Nav>Generate Alpha</Nav>
      <Nav>Our Platforms</Nav>
      <Nav>
        <TurnDownArrowRight />
        <span>Fountry</span>
      </Nav>
      <Nav>
        <TurnDownArrowRight />
        <span>gotham</span>
      </Nav>
      <Nav>
        <TurnDownArrowRight />
        <span>apollo</span>
      </Nav>
      <Nav>Offerings</Nav>
      <Nav>Impact Studies</Nav>
      <Nav>Careers</Nav>
      <Nav>About iTDAY</Nav>
    </nav>
  )
}

const Nav = (props: {
  link?: string,
  children: JSX.Element | JSX.Element[] | string,
  className?: string
}) => {
  return (
    <Link href={props?.link || routes.home}>
      <a {...props} className={'text-[2rem] hover:opacity-75 transition-all  flex space-x-2 tracking-wide' + ' ' + props.className}>{props.children}</a>
    </Link>
  )
}

export default Navigation;
